# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WYy9CBE2MmudIPLt6FHmp9qsSFf8Ilh
"""

import csv

def calculate_grade(average):
    if average >= 90:
        return "A+"
    elif average >= 80:
        return "A"
    elif average >= 70:
        return "B"
    elif average >= 60:
        return "C"
    elif average >= 50:
        return "D"
    else:
        return "F"

def process_students(input_file, output_file, report_file):
    students = []

    with open(input_file, "r") as file:
        reader = csv.DictReader(file)

        for row in reader:
            math = int(row["Math"])
            physics = int(row["Physics"])
            english = int(row["English"])

            total = math + physics + english
            average = total / 3
            grade = calculate_grade(average)

            student = {
                "Name": row["Name"],
                "Math": math,
                "Physics": physics,
                "English": english,
                "Total": total,
                "Average": round(average, 2),
                "Grade": grade
            }
            students.append(student)

    with open(output_file, "w", newline="") as file:
        fieldnames = [
            "Name",
            "Math",
            "Physics",
            "English",
            "Total",
            "Average",
            "Grade"
        ]

        writer = csv.DictWriter(file, fieldnames=fieldnames)

        writer.writeheader()
        writer.writerows(students)

    highest = max(students, key=lambda x: x["Average"])
    lowest = min(students, key=lambda x: x["Average"])

    with open(report_file, "w") as file:

        file.write("===== STUDENT PERFORMANCE REPORT =====\n\n")

        for student in students:

            file.write(
                f"Name: {student['Name']}\n"
                f"Total Marks: {student['Total']}\n"
                f"Average: {student['Average']}\n"
                f"Grade: {student['Grade']}\n"
                f"{'-' * 35}\n"
            )

        file.write("\n===== SUMMARY =====\n")

        file.write(
            f"Top Student: {highest['Name']} "
            f"({highest['Average']}%)\n"
        )

        file.write(
            f"Lowest Student: {lowest['Name']} "
            f"({lowest['Average']}%)\n"
        )

        file.write(
            f"Total Students: {len(students)}\n"
        )

    print("Automation completed successfully!")
    print(f"Processed CSV: {output_file}")
    print(f"Report generated: {report_file}")
    # Show the generated report on screen
    with open(report_file, "r") as file:
       report = file.read()

    print("\n===== GENERATED REPORT =====")
    print(report)

process_students(
    "input_students.csv",
    "processed_students.csv",
    "student_report.txt"
)